CREATE DATABASE POKEMON;

USE POKEMON;

CREATE TABLE POKEMONS(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMBER INT NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(200) NOT NULL,
    TYPE1 VARCHAR(100) NOT NULL,
    TYPE2 VARCHAR(100),
    HP INT NOT NULL,
    ATK INT NOT NULL,
    DEF INT NOT NULL,
    SPA INT NOT NULL,
    SPD INT NOT NULL,
    SPE INT NOT NULL,
    TOTAL_STATUS INT NOT NULL
 )
